version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge
    volumes:
          - db_data:/var/lib/mysql
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db_data: